version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # without :(bookmark), means do not try to map a folder against /app/node_modules inside the container
      - .:/app  # map current folder to /app inside the container

  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /app/node_modules # without :(bookmark), means do not try to map a folder against /app/node_modules inside the container
  #     - .:/app  # map current folder to /app inside the container
  #   command: ["npm", "run", "test"]